excluded:
  - AriesFramework/Pods
  - Sample
disabled_rules:
  - line_length
  - function_body_length
  - type_body_length
  - file_length
  - identifier_name
  - leading_whitespace
  - unused_closure_parameter
  - function_parameter_count
  - class_delegate_protocol
  - todo
  - large_tuple
