source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/naver/indy-sdk.git'
platform :ios, '15.0'

target 'SampleWalletSwiftUI' do
  use_frameworks!

  pod 'AriesFramework', :path => '../AriesFramework.podspec'
  pod 'Alamofire', '~> 5.2'
  pod 'SwiftyJSON', '~> 5.0'
end
