source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/naver/indy-sdk.git'
platform :ios, '15.0'

use_frameworks!
target 'AriesFramework' do
  pod 'Indy', '1.16.2'
  pod 'Base58Swift', '~> 2.1'
  pod 'WebSockets', '~> 0.5.0'
  pod 'CollectionConcurrencyKit', '~> 0.2.0'
end

target 'AriesFrameworkTests' do
  pod 'Criollo', '~> 0.5'
end
