source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/naver/indy-sdk.git'
platform :ios, '15.0'

use_frameworks!
target 'AriesFramework' do
  pod 'Indy', '1.16.2'
  pod 'Base58Swift', '~> 2.1'
  pod 'WebSockets', '~> 0.5.0'
  pod 'CollectionConcurrencyKit', '~> 0.2.0'
end

target 'AriesFrameworkTests' do
  pod 'Criollo', '~> 0.5'
end

post_install do |installer|
  desired_ios = '15.0'

  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          settings = config.build_settings
          actual = Gem::Version.new(settings['IPHONEOS_DEPLOYMENT_TARGET'])
          if actual < desired_ios
              settings['IPHONEOS_DEPLOYMENT_TARGET'] = desired_ios
          end
      end
  end
end
