source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/naver/indy-sdk.git'
platform :ios, '15.0'

target 'wallet-app-ios' do
  use_frameworks!

  pod 'AriesFramework', '~> 1.2'
end

post_install do |installer|
  desired_ios = '15.0'

  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          settings = config.build_settings
          actual = Gem::Version.new(settings['IPHONEOS_DEPLOYMENT_TARGET'])
          if actual < desired_ios
              settings['IPHONEOS_DEPLOYMENT_TARGET'] = desired_ios
          end
      end
  end
end
