name: Check PR

on:
  pull_request:
    branches: ["main"]

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1

  RunTests:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
        working-directory: AriesFramework
    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: pod install
    - name: Build
      run: xcodebuild build-for-testing CODE_SIGNING_ALLOWED=No -workspace AriesFramework.xcworkspace -scheme AriesFrameworkTests -sdk iphoneos -destination "platform=iOS Simulator,name=iPhone 14 Pro"
    - name: Run tests
      run: xcodebuild test-without-building CODE_SIGNING_ALLOWED=No -workspace AriesFramework.xcworkspace -scheme AriesFrameworkTests -sdk iphoneos -destination "platform=iOS Simulator,name=iPhone 14 Pro" -testPlan AriesFrameworkTests | xcpretty && exit ${PIPESTATUS[0]}
